# Generated by Django 3.1.7 on 2021-05-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Nombre')),
                ('shor_name', models.CharField(max_length=20, verbose_name='Nombre Corto')),
                ('anulate', models.BooleanField(default=False, verbose_name='Anulado')),
            ],
            options={
                'verbose_name': 'Mi departamento',
                'verbose_name_plural': 'Areas de la empresa',
                'ordering': ['-name'],
                'unique_together': {('name', 'shor_name')},
            },
        ),
    ]
